CREATE DATABASE vendas;
USE vendas;

-- MySQL Script generated by MySQL Workbench
-- Fri 10 Oct 2014 05:48:54 PM BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `ativo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `idcategoria` INT NOT NULL,
  `saldo` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_categoria_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  `status` CHAR(1) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL,
  `idcliente` INT(11) NOT NULL,
  `status` CHAR(1) NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_cliente1_idx` (`idcliente` ASC),
  INDEX `fk_venda_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendaitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendaitem` (
  `idproduto` INT(11) NOT NULL,
  `idvenda` INT NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `precopago` DECIMAL(8,2) NOT NULL,
  `qtd` INT NULL,
  PRIMARY KEY (`idproduto`, `idvenda`),
  INDEX `fk_produto_has_venda_venda1_idx` (`idvenda` ASC),
  INDEX `fk_produto_has_venda_produto1_idx` (`idproduto` ASC),
  CONSTRAINT `fk_produto_has_venda_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_venda_venda1`
    FOREIGN KEY (`idvenda`)
    REFERENCES `venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

START TRANSACTION;
INSERT INTO `usuario` (`idusuario`, `nome`, `email`, `senha`, `status`) VALUES (NULL, 'Admin', 'admin@admin.com', md5('abcadmin'), '1');

INSERT INTO `categoria` VALUES (1,'Refrigerantes','1'),(2,'Lanches','1');

INSERT INTO `cliente` VALUES (1,'Alisson Chiquitto','chiquitto@gmail.com','1');

INSERT INTO `produto` VALUES (1,'Coca Cola',3.50,'1',1,10),(2,'Pepsi',3.00,'1',1,15),(3,'X-Salada',10.50,'1',2,99),(4,'X-Bacon',12.00,'1',2,99);

INSERT INTO `venda` VALUES (1,'2016-10-03 00:00:00',1,'1',1);

INSERT INTO `vendaitem` VALUES (1,1,3.50,3.50,2),(3,1,10.50,10.50,1),(4,1,12.00,12.00,1);

COMMIT;

